const DEFAULT_MAP = [
  [
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "solid", color: "red" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
  ],
  [
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "solid", color: "red" },

    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "solid", color: "red" },

    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
  ],
  [
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "solid", color: "red" },

    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "solid", color: "red" },
  ],
  [
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
  ],
  [
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "solid", color: "red" },

    { type: "solid", color: "red" },

    { type: "solid", color: "red" },

    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
  ],
  [
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
  ],
  [
    { type: "solid", color: "red" },

    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "solid", color: "red" },

    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
  ],
  [
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "solid", color: "red" },

    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
    { type: "walk", color: "orange" },
    { type: "walk", color: "lightblue" },
  ],
];

export { DEFAULT_MAP };
